#!/usr/bin/env sh

antlr4_install() {
  mkdir -p ~/.emacs.d/antlr4
  if [ ! -f "$HOME/.emacs.d/antlr4/antlr-${ANTLR4_VERSION}-complete.jar" ]; then
    cd $HOME/.emacs.d/antlr4
    curl -O https://www.antlr.org/download/antlr-${ANTLR4_VERSION}-complete.jar
  fi
  antlr4_setenv
}

antlr4_uninstall() {
  echo_error "'antlr4_uninstall' not implemented"
}

antlr4_exist_p() {
  echo_error "'antlr4_exist_p' not implemented"
}

antlr4_info() {
  echo_error ""
}

antlr4_setenv() {
  if [ -f "$HOME/.emacs.d/antlr4/antlr-${ANTLR4_VERSION}-complete.jar" ]; then
    export CLASSPATH=".:$HOME/.emacs.d/antlr4/antlr-${ANTLR4_VERSION}-complete.jar:$CLASSPATH"
    alias antlr4='java -jar $HOME/.emacs.d/antlr4/antlr-${ANTLR4_VERSION}-complete.jar'
    alias grun='java org.antlr.v4.gui.TestRig'
  fi
}
antlr4_setenv
