#!/usr/bin/env sh

basedev_install_tools() {
    get_os_type
    case $OME_OS in
        # Linux
        # $OS_DEBIAN) ;;
        # $OS_UBUNTU) ;;
        $OS_DEBIAN|$OS_UBUNTU)
            sudo apt install -y build-essential \
                 make ninja-build cmake \
                 autogen automake autoconf libtool libtool-bin \
                 pkg-config
            ;;
        # $OS_REDHAT) ;;
        # $OS_FEDORA) ;;
        $OS_REDHAT|$OS_FEDORA)
            sudo yum groupinstall -y "Development Tools"
            sudo yum install -y gcc gcc-c++ make ninja-build cmake \
                 autogen automake autoconf libtool \
                 pkg-config
            ;;
        $OS_ARCH)
            trizen -S base-devel make ninja cmake \
                   autogen automake autoconf libtool \
                   pkg-config
            ;;
        $OS_GENTOO) ;;
        $OS_SUSE)
            # sudo zypper refresh
            # sudo zypper update
            # zypper info -t pattern devel_basis
            sudo zypper install -t pattern devel_basis
            sudo zypper install make ninja cmake \
                 autogen automake autoconf libtool \
                 pkg-config
            ;;
        $OS_SLACKWARE) ;;
        $OS_NIXOS) ;;
        $OS_VOID) ;;
        $OS_ALPINE) ;;
        $OS_MAGEIA) ;;
        $OS_SLITAZ) ;;
        $OS_GUIXSD) ;;
        # Unix
        $OS_MACOS)
            brew install gcc-core gcc-g++ \
                 make ninja cmake \
                 autogen automake autoconf libtool \
                 pkg-config
            ;;
        $OS_AIX) ;;
        $OS_SOLARIS) ;;
        $OS_FREEBSD)
            sudo pkg install gcc gmake ninja cmake \
                 autogen automake autoconf libtool \
                 pkgconf
            ;;
        $OS_OPENBSD) ;;
        $OS_NETBSD) ;;
        $OS_DFBSD) ;;
        # Windows
        $OS_CYGWIN)
            apt install gcc-core gcc-g++ \
                make ninja cmake \
                autogen automake autoconf libtool \
                pkg-config
            ;;
        $OS_MSYS2)
            # pacman -S mingw-w64-x86_64-make mingw-w64-x86_64-gcc mingw-w64-x86_64-nasm \
                   # mingw-w64-x86_64-make mingw-w64-x86_64-ninja \
                   # mingw-w64-x86_64-libtool mingw-w64-x86_64-pkg-config \
            pacman -S base-devel msys2-devel gcc gcc-libs\
                   make ninja cmake \
                   autogen automake autoconf libtool \
                   pkg-config
            # cross
            # pacman -S mingw-w64-cross-gcc mingw-w64-x86_64-pdcurses
            # mingw-w64-x86_64-python2 mingw-w64-x86_64-python2-pip
            # mingw-w64-x86_64-python3 mingw-w64-x86_64-python3-pip
            # mingw-w64-x86_64-emacs mingw-w64-x86_64-ttf-dejavu
            ;;
        # Other
        $OS_UNKNOW) ;;
    esac
}

basedev_install() {
    # gcc clang make m4 automake pkg-config"
    
    # libdn2 libuv libason-devel
    # 
    # libgmime glibc
    # libiconv
    # sed awk grep tar zip unzip 7zip flex gawke bison bc mt
    # guile rush tramp libc scm screen

    basedev_install_tools
}

basedev_uninstall() {
    echo_error "'basedev_uninstall' not implemented"
}

basedev_exist_p() {
    echo_error "'basedev_exist_p' not implemented"
}

# if [ "$OME_OS" == "$OS_MSYS2" ]; then
#     # MAKE_TYPE="MSYS Makefiles"
#     OME_MAKE="Ninja"
# else
#     OME_MAKE="Ninja"
#     MAKE_PROG="make"
# fi

export OME_MAKE="Ninja"
export MAKE_PROG="make"
basedev_info() {
    # ome_get_version gcc "GCC_VERSION"
    # echo_kv "C/C++" "$GCC_VERSION|$CLANG_VERSION"
    # echo_kv "CTool" "pkg-config $PKGCONF_VERSION|$LIBTOOL_VERSION"
    # echo_kv "Make" "$MAKE_VERSION|$AUTOMAKE_VERSION|$AUTOCONF_VERSION"

    ome_show "GCC" "`ome_fetch_version gcc`"
    ome_show "Clang" "`ome_fetch_version clang`"
    ome_show "Make" "`ome_fetch_version make` | `ome_fetch_version cmake` (default: $OME_MAKE)"
    # ome_show "Auto" "`ome_fetch_version autogen` | `ome_fetch_version automake` | `ome_fetch_version autoconf`"
    # ome_show "CTool" "pkg-config `ome_fetch_version pkg-config` | `ome_fetch_version libtool`" #`ome_fetch_version m4` | 
}
