#!/usr/bin/env sh

chez_install() {
    github_upgrade cisco/ChezScheme $OME_REPO/ChezScheme
    cd $OME_REPO/ChezScheme
	#--installprefix=$OME_PREFIX
    ./configure --help

    if [ "$OME_OS" = "$OS_CYGWIN" ] || [ "$OME_OS" = "$OS_MSYS2" ]; then
	    rm -rf ./Makefile
	    rm -rf ./a6nt
    fi

    ./configure --installprefix=$OME_PREFIX
    #--temproot=$HOME/chez
    if [ "$OME_OS" = "$OS_CYGWIN" ] || [ "$OME_OS" = "$OS_MSYS2" ]; then
	    cd a6nt/c
        ./make.bat
        cd ..
    fi
    make
    make install
    chez_setenv
}

chez_uninstall() {
    echo_error "'chez_uninstall' not implemented"
}

chez_exist_p() {
    echo_error "'chez_exist_p' not implemented"
}

chez_info() {
    if [ "`command -v scheme`" != "" ]; then
        ome_show "Scheme" "ChezScheme `ome_fetch_version scheme`"
    fi
}

chez_setenv() {
    if [ -d "$OME_REPO/ChezScheme/a6nt/bin/a6nt" ]; then
        # $OME_REPO/vcpkg
        export PATH=$OME_REPO/ChezScheme/a6nt/bin/a6nt:$PATH
    fi
}
chez_setenv
