#!/usr/bin/env sh

clasp_install() {
    get_os_type
    case $OME_OS in
        # Linux
        # $OS_DEBIAN) ;;
        # $OS_UBUNTU) ;;
        $OS_DEBIAN|$OS_UBUNTU)
            sudo apt install -y gcc g++ llvm clang-6.0 libclang-6.0-dev \
                 cmake libgc-dev libgmp-dev binutils-gold binutils-dev zlib1g-dev \
                 libncurses-dev libboost-filesystem-dev libboost-regex-dev \
                 libboost-date-time-dev libboost-program-options-dev \
                 libboost-system-dev libboost-iostreams-dev libunwind-dev liblzma-dev sbcl
            ;;
        # $OS_REDHAT) ;;
        # $OS_FEDORA) ;;
        $OS_REDHAT|$OS_FEDORA) ;;
        $OS_ARCH) ;;
        $OS_GENTOO) ;;
        $OS_SUSE) ;;
        $OS_SLACKWARE) ;;
        $OS_NIXOS) ;;
        $OS_VOID) ;;
        $OS_ALPINE) ;;
        $OS_MAGEIA) ;;
        $OS_SLITAZ) ;;
        $OS_GUIXSD) ;;
        # Unix
        $OS_MACOS) ;;
        $OS_AIX) ;;
        $OS_SOLARIS) ;;
        $OS_FREEBSD) ;;
        $OS_OPENBSD) ;;
        $OS_NETBSD) ;;
        $OS_DFBSD) ;;
        # Windows
        $OS_CYGWIN) ;;
        $OS_MSYS2) ;;
        # Other
        $OS_UNKNOW) ;;
    esac

    github_upgrade clasp-developers/clasp $OME_CACHE/clasp
    cd $OME_CACHE/clasp/
    ./waf configure
    ./waf build_cboehm
}

clasp_uninstall() {
    echo_error "'clasp_uninstall' not implemented"
}

clasp_exist_p() {
    echo_error "'clasp_exist_p' not implemented"
}

clasp_info() {
    echo_error ""
}
