#!/usr/bin/env sh

clj_install() {
    if [ "`command -v clj`" = "" ]; then
        cd $HOME/Downloads/
        rm -rf ./linux-install-1.10.0.403.sh
        curl -O https://download.clojure.org/install/linux-install-1.10.0.403.sh
        chmod +x linux-install-1.10.0.403.sh
        ./linux-install-1.10.0.403.sh --prefix $OME_PREFIX
    fi

    if [ "`command -v lein`" = "" ]; then
        cd $OME_PREFIX/bin/
        rm -rf ./lein
        wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
        chmod +x ./lein
        lein --version
    else
        lein upgrade
    fi

    if [ "`command -v boot`" = "" ]; then
        cd $OME_PREFIX/bin/
        curl -fsSLo boot https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh
        chmod +x ./boot
        boot --version
    fi
}

clj_uninstall() {
    echo_error "'clj_uninstall' not implemented"
}

clj_exist_p() {
    echo_error "'clj_exist_p' not implemented"
}

clj_info() {
    ome_info "clj" "`ome_fetch_version lein | cut -d ' ' -f 1-2`"
}
