#!/usr/bin/env sh

clj_install() {
    ome_check_install "java" "jvm"

    # https://www.clojure.org/guides/getting_started
    # https://clojure.org/guides/deps_and_cli
    tip "install clojure cli"
    if [ "`command -v clojure`" = "" ]; then
        cd $HOME/Downloads/
        CLI_FILE=linux-install-${CLOJURE_VERSION}.sh
        zipkg=clojure-tools-${CLOJURE_VERSION}.tar.gz
        if [ ! -f "$HOME/Downloads/$CLI_FILE" ]; then
            # rm -rf ./$CLI_FILE
            curl -O https://download.clojure.org/install/$CLI_FILE
            replace_str "curl -O" "# curl -O" $HOME/Downloads/$CLI_FILE "0"
        fi

        chmod +x ./$CLI_FILE
        mkdir -p $OME_PREFIX/lib/clojure/libexec/
        ./$CLI_FILE --prefix $OME_PREFIX
    fi

    tip "install leiningen"
    mkdir -p $HOME/.lein/self-installs/
    if [ ! -f $HOME/.lein/self-installs/leiningen-2.9.1-standalone.jar ]; then
        echo "use cache:"
        cp -u $HOME/.emacs.d/files/leiningen-2.9.1-standalone.jar $HOME/.lein/self-installs/
    fi

    if [ "`command -v lein`" = "" ]; then
        tip "install leiningen"
        cd $OME_PREFIX/bin/
        rm -rf ./lein
        wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
        chmod +x ./lein
        lein --version
    else
        lein --version
        # lein upgrade
    fi

    # tip "install boot" #obslote
    # if [ "`command -v boot`" = "" ]; then
        # tip "install boot"
        # cd $OME_PREFIX/bin/
        # curl -fsSLo boot https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh
        # chmod +x ./boot
        # boot --version
    # fi
}

clj_uninstall() {
    echo_error "'clj_uninstall' not implemented"
}

clj_exist_p() {
    echo_error "'clj_exist_p' not implemented"
}

clj_info() {
    ome_show "CLJ" "`ome_fetch_version lein | cut -d ' ' -f 1-2`"
}

clj_publish_settings() {
    if [ ! -f $HOME/.lein/init.clj ]; then
        read -p "please input your username with clojas:" username
	    read -sp "please input your password with clojas:" password
        echo ""
        echo '(def settings' >> $HOME/.lein/init.clj
        echo '{:deploy-repositories {"clojars-https" {:url "https://clojars.org/repo"' >> $HOME/.lein/init.clj
        echo "                                         :username $username" >> $HOME/.lein/init.clj
        echo "                                         :password $password}}})" >> $HOME/.lein/init.clj
    fi
}
