#!/usr/bin/env sh

cljs_install() {
    tip "install planck"
    github_upgrade planck-repl/planck $OME_CACHE/planck
    cd $OME_CACHE/planck/
    script/build
    script/install --prefix $OME_PREFIX
    
    ome_check_install "npm" "nodejs"
    
    tip "install lumo-cljs"
    npm install -g lumo-cljs

    tip "install calvin"
    npm install -g calvin-cljs
    npm install -g shelljs

}

cljs_uninstall() {
    echo_error "'cljs_uninstall' not implemented"
}

cljs_exist_p() {
    echo_error "'cljs_exist_p' not implemented"
}

cljs_info() {
    if [ "`command -v elixir`" != "" ]; then
        ome_info "Erlang" "`elixir --version 2>&1 | head -n 1 | cut -d ' ' -f 1-3`"
        ome_info "Elixir" "`elixir --version 2>&1 | tail -n 1 | cut -d ' ' -f 1-3`"
    fi
}
