#!/usr/bin/env sh

elixir_install_language_server() {
    github_upgrade JakeBecker/elixir-ls $OME_REPO/elixir-ls
    cd $OME_REPO/elixir-ls/
    mix deps.get
    # Shall I install rebar3? (if running non-interactively, use "mix local.rebar --force") [Yn]
    mix compile
    mix elixir_ls.release -o $HOME/elixier-ls-release
}

elixir_install_kiex() {
    \curl -sSL https://raw.githubusercontent.com/taylor/kiex/master/install | bash -s
    test -s "$HOME/.kiex/scripts/kiex" && source "$HOME/.kiex/scripts/kiex"
}

elixir_install_git() {
    ome_check_install "erl" "erlang"
    github_upgrade elixir-lang/elixir $OME_REPO/elixir
    cd $OME_REPO/elixir
    make
    # make test
}

elixir_install() {
    tip "install elixir(git)"
    # elixir_install_kiex
    elixir_install_git

    tip "install elixir language server"
    elixir_install_language_server
}


elixir_uninstall() {
    echo_error "'elixir_uninstall' not implemented"
}

elixir_exist_p() {
    echo_error "'elixir_exist_p' not implemented"
}

elixir_info() {
    if [ "`command -v elixir`" != "" ]; then
        ome_show "Erlang" "`elixir --version 2>&1 | head -n 1 | cut -d ' ' -f 1-3`"
        ome_show "Elixir" "`elixir --version 2>&1 | tail -n 1 | cut -d ' ' -f 1-3`"
    fi
    
}

export PATH=$OME_REPO/elixir/bin:$PATH
test -s "$HOME/.kiex/scripts/kiex" && source "$HOME/.kiex/scripts/kiex"
