#!/usr/bin/env sh

ethr_install() {
    github_upgrade Microsoft/ethr $OME_CACHE/ethr
    cd $OME_CACHE/ethr/
    dep ensure -v
    go build
}

ethr_uninstall() {
    echo_error "'ethr_uninstall' not implemented"
}

ethr_exist_p() {
    echo_error "'ethr_exist_p' not implemented"
}

ethr_info() {
    echo_error ""
}
