#!/usr/bin/env sh

font_install() {
    cd $HOME/Downloads/
    local pkgname=JetBrainsMono-${JETBRINS_FONT_VERSION}
    local zipkg=${pkgname}.zip

    if [ ! -f "$HOME/Downloads/$zipkg" ]; then
        wget https://download.jetbrains.8686c.com/fonts/${zipkg}
    fi
    if [ ! -d "$HOME/Downloads/$pkgname" ]; then
        unzip ./JetBrainsMono-${JETBRINS_FONT_VERSION}.zip -d ./
    fi

    if [ "$OME_OS" = "$OS_CYGWIN" ] || [ "$OME_OS" = "$OS_MSYS2" ]; then
        # cp -f ./JetBrainsMono-${JETBRINS_FONT_VERSION}/ttf/* "${USERPROFILE}/AppData/Local/Microsoft/Fonts/"
        echo "windows"
        # echo A^|xcopy `cygpath -w ./JetBrainsMono-${JETBRINS_FONT_VERSION}/ttf/*` "${SYSTEMROOT}/Fonts/"
        # cp -f ./JetBrainsMono-${JETBRINS_FONT_VERSION}/ttf/* "${SYSTEMROOT}/Fonts/"
        cd "$HOME/Downloads/$pkgname"
        for file in `ls "$HOME/Downloads/$pkgname/ttf"`
        do
            local basename=${file%.*}
            local extname=${file##*.}
            if [ "$extname" = "ttf" ]; then
                # cp -f ./ttf/$file "${SYSTEMROOT}/Fonts/"
                local REGPATH='"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts"'
                echo reg add ${REGPATH} /v "\"${basename} (TrueType)\"" /t REG_SZ /d "${file}" /f

                # local REGPATH="\"HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts\""
                # REG ADD ${REGPATH} /v "\"${basename} (TrueType)\"" /t REG_SZ /d "\"${file}\"" /f
                
            fi
        done
    else
        cp -f ./JetBrainsMono-${JETBRINS_FONT_VERSION}/ttf/* $HOME/.local/share/fonts/
        fc-cache -f -v
    fi
}

font_uninstall() {
    echo_error "'font_uninstall' not implemented"
}

font_exist_p() {
    echo_error "'font_exist_p' not implemented"
}

font_info() {
    echo_error ""
}
