#!/usr/bin/env sh

goto_define() {
    . $OME_REPO/goto/goto.sh

    tip "setting goto dir"
    goto -u ome
    goto -r ome $OME_ROOT

    goto -u emacs
    goto -r emacs $OME_EMACS

    goto -u emacs.d
    goto -r emacs.d $HOME/.emacs.d/

    goto -u prefix
    goto -r prefix $OME_PREFIX

    goto -u repo
    goto -r repo $OME_REPO

    goto -u plugin
    goto -r plugin $OME_ROOT/plugins/
    

    goto -u ws
    goto -r ws $OME_WS

    goto -u book
    goto -r book $OME_BOOK

    goto -u proj
    goto -r proj $OME_PROJ

    goto -u hello
    goto -r hello $OME_WS/hello

    goto -l
}

goto_install() {
    github_upgrade iridakos/goto $OME_REPO/goto
    cd $OME_REPO/goto
    chmod +x ./*.sh

    goto_define
}

goto_uninstall() {
    echo_error "'goto_uninstall' not implemented"
}

goto_exist_p() {
    echo_error "'goto_exist_p' not implemented"
}

goto_info() {
    echo_error ""
}

if [ -d $OME_REPO/goto ]; then
    . $OME_REPO/goto/goto.sh
    # goto_define
fi
