#!/usr/bin/env sh

goto_define() {
    goto -r ome $HOME/.oh-my-emacs/
    goto -r ws $HOME/workspace/
    goto -r plugins $HOME/workspace/bin/plugins/common/
}

goto_install() {
    github_upgrade iridakos/goto $OME_CACHE/goto
    cd $OME_CACHE/goto
    chmod +x ./*.sh

    goto_define
}

goto_uninstall() {
    echo_error "'goto_uninstall' not implemented"
}

goto_exist_p() {
    echo_error "'goto_exist_p' not implemented"
}

goto_info() {
    echo_error ""
}

if [ -d $OME_CACHE/goto ]; then
    # export PATH=$OME_CACHE/goto:$PATH
    . $OME_CACHE/goto/goto.sh
    goto_define
fi
