#!/usr/bin/env sh

init_install() {
	. $OME_ROOT/install.sh
}

init_uninstall() {
    echo_error "'basedevel_uninstall' not implemented"
}

init_exist_p() {
    echo_error "'basedevel_exist_p' not implemented"
}

init_info() {
    echo_error ""
}

