#!/usr/bin/env sh

input_install() {
  get_os_type
  case $OME_OS in
    # Linux
    # $OS_DEBIAN) ;;
    # $OS_UBUNTU) ;;
    $OS_DEBIAN|$OS_UBUNTU) ;;
    # $OS_REDHAT) ;;
    # $OS_FEDORA) ;;
    $OS_REDHAT|$OS_FEDORA) ;;
    $OS_ARCH) trizen -S ibus ibus-sunpinyin;;
    $OS_GENTOO) ;;
    $OS_SUSE) ;;
    $OS_SLACKWARE) ;;
    $OS_NIXOS) ;;
    $OS_VOID) ;;
    $OS_ALPINE) ;;
    $OS_MAGEIA) ;;
    $OS_SLITAZ) ;;
    $OS_GUIXSD) ;;
    # Unix
    $OS_MACOS) ;;
    $OS_AIX) ;;
    $OS_SOLARIS) ;;
    $OS_FREEBSD) ;;
    $OS_OPENBSD) ;;
    $OS_NETBSD) ;;
    $OS_DFBSD) ;;
    # Windows
    $OS_CYGWIN) ;;
    $OS_MSYS2) ;;
    # Other
    $OS_UNKNOW) ;;
  esac

  find_str "ibus-daemon" $HOME/.profile
  if [ $? -eq 0 ]; then
    echo "export GTK_IM_MODULE=ibus" >> $HOME/.profile
    echo "export XMODIFIERS=@im=ibus" >> $HOME/.profile
    echo "export QT_IM_MODULE=ibus" >> $HOME/.profile
    echo "ibus-daemon -d -x" >> $HOME/.profile
  fi
}

input_uninstall() {
  echo_error "'input_uninstall' not implemented"
}

input_exist_p() {
  echo_error "'input_exist_p' not implemented"
}

input_info() {
  echo_error ""
}
