#!/usr/bin/env sh

janet_install() {
    github_upgrade janet-lang/janet $OME_REPO/janet
    cd $OME_REPO/janet
    make
    make test
    make repl
}

janet_uninstall() {
    echo_error "'janet_uninstall' not implemented"
}

janet_exist_p() {
    echo_error "'janet_exist_p' not implemented"
}

janet_info() {
    echo_error ""
}
