#!/usr/bin/env sh

libuv_install() {
    get_os_type
    case $OME_OS in
        # Linux
        $OS_DEBIAN) ;;
        $OS_UBUNTU) ;;
        $OS_REDHAT) ;;
        $OS_FEDORA) ;;
        $OS_GENTOO) ;;
        $OS_ARCH) ;;
        $OS_ALPINE) ;;
        $OS_VOID) ;;
        # Unix
        $OS_MACOS) ;;
        $OS_AIX) ;;
        $OS_SORLARIS) ;;
        $OS_FREEBSD) ;;
        $OS_OPENBSD) ;;
        # Windows
        $OS_CYGWIN) ;;
        $OS_MSYS2) ;;
        # Other
        $OS_UNKNOW) ;;
    esac
    github_upgrade libuv/libuv $OME_PREFIX/libuv
	#mkdir -p $OME_PREFIX/libuv/build

    #github_ssh_upgrade damon-kwok/libuv $PROJ_ROOT/c/libuv
    #mkdir -p $PROJ_ROOT/c/libuv/build

    # cd $PROJ_ROOT/c/libuv/build/
    # cmake .. -G "$OME_MAKE" \
	      # -DCMAKE_INSTALL_PREFIX=$OME_PREFIX
    # cmake --build . --use-stderr --config Release --target install -- -j4

    #cd $PROJ_ROOT/c/libuv/
	cd $OME_PREFIX/libuv

    chmod +x ./autogen.sh
    ./autogen.sh
    ./configure --prefix=$OME_PREFIX
    # make
    #--disable-dependency-tracking
    make check
    make install
}

libuv_uninstall() {
    echo_error "'libuv_uninstall' not implemented"
}

libuv_exist_p() {
    echo_error "'libuv_exist_p' not implemented"
}

libuv_info() {
    echo_error ""
}
