#!/usr/bin/env sh

nvidia_install() {
  get_os_type
  case $OME_OS in
    # Linux
    $OS_DEBIAN) ;;
    $OS_UBUNTU)
      # if [ ! -f /etc/apt/sources.list.d/graphics-drivers-ubuntu-ppa-xenial.list ]; then
		  tip "add ppa:nvidia-driver"
		  sudo add-apt-repository -y ppa:graphics-drivers/ppa
		  # fi
      # readp "install nvidia-driver?"
			# if [ $? -eq 1 ]; then
      apt search nvidia-driver
			sudo apt install -y nvidia-driver #-390
			# nomodeset
			readp "nomodeset for grub.cfg?"
			if [ $? -eq 1 ]; then
				# replace-str "quiet splash" "nomodeset" /boot/grub/grub.cfg 1
				sudo perl -pi -e 's|quiet splash|nomodeset|g' /boot/grub/grub.cfg
			fi
			# fi
      ;;
    # $OS_DEBIAN|$OS_UBUNTU) ;;
    # $OS_REDHAT) ;;
    # $OS_FEDORA) ;;
    $OS_REDHAT|$OS_FEDORA)
      yum install nvidia-driver ;;
    $OS_ARCH)
      kver=`uname -r|cut -d"." -f1-2`
      pkg_name="linux${kver//./}-nvidia"
      tip "install ${pkg_name}"
      sudo pacman -S ${pkg_name}
      ;;
    $OS_GENTOO) ;;
    $OS_SUSE)
      tip "add nvidia repo:"
      readp "tumbleweed?"
      if [ $? -eq 1 ]; then
        sudo zypper addrepo -f https://download.nvidia.com/opensuse/tumbleweed/ nvidia
      else
        sudo zypper addrepo -f https://download.nvidia.com/opensuse/leap/${releasever} nvidia
      fi
      sudo zypper install x11-video-nvidiaG05
      ;;
    $OS_SLACKWARE) ;;
    $OS_NIXOS) ;;
    $OS_VOID) ;;
    $OS_ALPINE) ;;
    $OS_MAGEIA) ;;
    $OS_SLITAZ) ;;
    $OS_GUIXSD) ;;
    # Unix
    $OS_MACOS) ;;
    $OS_AIX) ;;
    $OS_SOLARIS) ;;
    $OS_FREEBSD) ;;
    $OS_OPENBSD) ;;
    $OS_NETBSD) ;;
    $OS_DFBSD) ;;
    # Windows
    $OS_CYGWIN) ;;
    $OS_MSYS2) ;;
    # Other
    $OS_UNKNOW) ;;
  esac
}

nvidia_uninstall() {
  echo_error "'nvidia_uninstall' not implemented"
}

nvidia_exist_p() {
  echo_error "'nvidia_exist_p' not implemented"
}

nvidia_info() {
  echo_error ""
}
