#!/usr/bin/env sh

link_init_el() {
    tip "link"
    bkdir=$HOME/emacs-config-backup/`date +%Y-%m-%d@%H-%M-%S`
    mkdir -p $bkdir

    if [ -e $HOME/.emacs ]; then
	    mv $HOME/.emacs $bkdir
        echo "your .emacs backup to '$bkdir'"
    fi

    if [ ! -d "$HOME/.emacs.d/.git/" ]; then
        mv $HOME/.emacs.d/ $bkdir
        echo "your .emacs.d/ backup to '$bkdir'"
    fi
    gitee_upgrade damon-kwok/emacs.d $HOME/.emacs.d
    chmod +x $HOME/.emacs.d/on-hook.sh
    $HOME/.emacs.d/on-hook.sh pull

    # if [ -r $HOME/emacs-config ]; then
        # echo "mv 2"
	    # mv $HOME/emacs-config $bkdir
    # fi

    rm -rf $HOME/emacs-config

    tip "link .emacs"
    cp -a $HOME/.oh-my-emacs/emacs-config/init.el $HOME/.emacs 
    ln -s $HOME/.oh-my-emacs/emacs-config $HOME/emacs-config 
}

oh_my_emacs_install() {
    github_upgrade damon-kwok/oh-my-emacs $HOME/.oh-my-emacs
    link_init_el
}

oh_my_emacs_uninstall() {
    echo_error "'oh_my_emacs_uninstall' not implemented"
}

oh_my_emacs_exist_p() {
    echo_error "'oh_my_emacs_exist_p' not implemented"
}

oh_my_emacs_info() {
    echo_error ""
}
