#!/usr/bin/env sh

pmccabe_install() {
    github_upgrade datacom-teracom/pmccabe $DEV_ROOT/pmccabe
    cd $DEV_ROOT/pmccabe/
    make
    
    chmod +x $DEV_ROOT/pmccabe/pmccabe
    chmod +x $DEV_ROOT/pmccabe/decomment
    
    cp -rf $DEV_ROOT/pmccabe/pmccabe $OME_PREFIX/bin/
    cp -rf $DEV_ROOT/pmccabe/decomment $OME_PREFIX/bin/
}

pmccabe_uninstall() {
    echo_error "'pmccabe_uninstall' not implemented"
}

pmccabe_exist_p() {
    echo_error "'pmccabe_exist_p' not implemented"
}

pmccabe_info() {
    echo_error ""
}
