#!/usr/bin/env sh

pmccabe_install() {
    github_upgrade datacom-teracom/pmccabe $OME_CACHE/pmccabe
    cd $OME_CACHE/pmccabe/
    make
    
    chmod +x $OME_CACHE/pmccabe/pmccabe
    chmod +x $OME_CACHE/pmccabe/decomment
    
    cp -rf $OME_CACHE/pmccabe/pmccabe $OME_PREFIX/bin/
    cp -rf $OME_CACHE/pmccabe/decomment $OME_PREFIX/bin/
}

pmccabe_uninstall() {
    echo_error "'pmccabe_uninstall' not implemented"
}

pmccabe_exist_p() {
    echo_error "'pmccabe_exist_p' not implemented"
}

pmccabe_info() {
    echo_error ""
}
