#!/usr/bin/env sh

pony_install() {
    # curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/ponylang/ponyup/latest-release/ponyup-init.sh | sh
    # ponyup update ponyc release
    # ponyup update ponyc nightly
    github_upgrade ponylang/ponyc $OME_REPO/ponyc-git 0
    cd $OME_REPO/ponyc-git

    make libs
    make configure
    make build
    # make test
    # sudo make install
    pony_setenv

    github_upgrade ponylang/pony-stable $OME_REPO/pony-stable
    cd $OME_REPO/pony-stable
    make
    pony_setenv
}

pony_uninstall() {
    echo_error "'pony_uninstall' not implemented"
}

pony_exist_p() {
    echo_error "'pony_exist_p' not implemented"
}

pony_info() {
    if [ "`command -v ponyc`" != "" ]; then
        ome_show "Pony" "`ome_fetch_version ponyc`"
    fi
}

pony_setenv() {
    if [ -d "$OME_REPO/ponyc-git/build/release" ]; then
        export PATH=$OME_REPO/ponyc-git/build/release:$PATH
    fi

    if [ -d "$OME_REPO/pony-stable/build/release" ]; then
        export PATH=$OME_REPO/pony-stable/build/release:$PATH
    fi
}
pony_setenv
