#!/usr/bin/env sh

r_install() {
get_os_type
case $OME_OS in
    # Linux
    # $OS_DEBIAN) ;;
    # $OS_UBUNTU) ;;
    $OS_DEBIAN|$OS_UBUNTU) sudo apt install r-base ;;
    # $OS_REDHAT) ;;
    # $OS_FEDORA) ;;
    $OS_REDHAT|$OS_FEDORA) sudo yum install r-base ;;
    $OS_ARCH) sudo pacman -S r-base ;;
    $OS_GENTOO) ;;
    $OS_SUSE) sudo zypper install r-base ;;
    $OS_SLACKWARE) ;;
    $OS_NIXOS) ;;
    $OS_VOID) ;;
    $OS_ALPINE) ;;
    $OS_MAGEIA) ;;
    $OS_SLITAZ) ;;
    $OS_GUIXSD) ;;
    # Unix
    $OS_MACOS) brew install r-base ;;
    $OS_AIX) ;;
    $OS_SOLARIS) ;;
    $OS_FREEBSD) sudo pkg install r-base ;;
    $OS_OPENBSD) ;;
    $OS_NETBSD) ;;
    $OS_DFBSD) ;;
    # Windows
    $OS_CYGWIN) apt install r-base ;;
    $OS_MSYS2) pacman -S r-base ;;
    # Other
    $OS_UNKNOW) ;;
esac

}

r_uninstall() {
    echo_error "'r_uninstall' not implemented"
}

r_exist_p() {
    echo_error "'r_exist_p' not implemented"
}

r_info() {
    echo_error ""
}

