#!/usr/bin/env sh

# rustup china
# https://mirrors.ustc.edu.cn/help/rust-static.html
# http://www.cnblogs.com/hadex/p/8568796.html

# Rust Creates china mirror
# https://mirrors.ustc.edu.cn/help/crates.io-index.html

rust_install() {
  local oldir=`pwd`

  tip "set rust install env:"
  mkdir -p $HOME/.rustup
  # https://github.com/rust-lang/rustup#environment-variables

  # ustc
  export RUSTUP_DIST_SERVER=https://mirrors.ustc.edu.cn/rust-static
  export RUSTUP_UPDATE_ROOT=https://mirrors.ustc.edu.cn/rust-static/rustup

  # tuna
  # export RUSTUP_DIST_SERVER=https://mirrors.tuna.tsinghua.edu.cn/rustup
  # export RUSTUP_UPDATE_ROOT=https://mirrors.tuna.tsinghua.edu.cn/rustup/rustup

  export RUSTUP_HOME=$HOME/.rustup
  export CARGO_HOME=$HOME/.cargo

  readp "cargo: use china mirror?"
  if [ $? -eq 1 ]; then
    echo "yes"
  fi
  tip "set cargo mirror"
  if [ ! -f $HOME/.cargo/config ]; then
    mkdir -p $HOME/.cargo
    echo "[source.crates-io]" >> $HOME/.cargo/config
    echo 'registry = "https://github.com/rust-lang/crates.io-index"' >> $HOME/.cargo/config

    # echo "replace-with = 'tuna'" >> $HOME/.cargo/config
    # echo "" >> $HOME/.cargo/config
    # echo "[source.tuna]" >> $HOME/.cargo/config
    # echo "registry = 'https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git'" >> $HOME/.cargo/config

    echo "replace-with = 'ustc'" >> $HOME/.cargo/config
    echo "" >> $HOME/.cargo/config
    echo "[source.ustc]" >> $HOME/.cargo/config
    #echo 'registry = "git://mirrors.ustc.edu.cn/crates.io-index"' >> $HOME/.cargo/config
    echo 'registry = "https://mirrors.ustc.edu.cn/crates.io-index"' >> $HOME/.cargo/config
  fi

  tip "install rust"
  if [ "`command -v rustup`" = "" ]; then
    tip "install rustup"

    readp "install rustup with china mirror?"
    if [ $? -eq 1 ]; then
      cd $HOME/.cargo/
      rm -rf ./rustup-init.sh

      tip "wget https://sh.rustup.rs"
      wget https://cdn.jsdelivr.net/gh/rust-lang-nursery/rustup.rs/rustup-init.sh
      perl -pi -e 's|"https://static.rust-lang.org/rustup/dist"|"https://mirrors.ustc.edu.cn/rust-static/rustup"|g' ./rustup-init.sh
      # wget https://sh.rustup.rs/
      # perl -pi -e 's|"https://static.rust-lang.org/rustup/dist"|"https://mirrors.tuna.tsinghua.edu.cn/rustup/dist"|g' ./rustup-init.sh

      tip "rustup-init"
      chmod +x ./rustup-init.sh
      sh ./rustup-init.sh
    else
      # curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly
      curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable
      # curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
    fi

    tip "rust set env"
    rust_setenv
  else
    tip "rustup self update"
    rustup self update
    tip "rustup update"
    rustup update
  fi

  # tip "rustup install stable"
  # rustup toolchain add stable
  # tip "rustup default stable"
  # rustup default stable

  # tip "rustup install beta"
  # rustup toolchain add beta
  # tip "rustup default beta"
  # rustup default beta

  tip "rustup install nightly"
  rustup toolchain add nightly
  tip "rustup default nightly"
  rustup default nightly

  # tip "rustup component add rust-src"
  # rustup component add rust-src

  tip "install rust language server: (RLS)"
  # rustup component add clippy rls rust-analysis rust-src
  rustup component add --toolchain nightly clippy rls rust-analysis rust-src

  tip "rust set env"
  rust_setenv

  # tip "install tool:racer"
  # cargo install --force racer
  # cargo install racer

  tip "install tool:ripgrep"
  # cargo install --force ripgrep
  cargo install ripgrep
  cd $oldir
}


rust_uninstall() {
  echo_error "'rust_uninstall' not implemented"
}

rust_exist_p() {
  echo_error "'rust_exist_p' not implemented"
}

rust_info() {
  if [ "`command -v rustup`" != "" ]; then
    ome_show "Rust" "`ome_fetch_version rustc` |  `rustup -V | cut -c 1-13`"
  fi
  # if [ "`command -v rustup`" != "" ]; then
  # echo_kv "Rustup" "`rustup -V | head -n 1`"
  # fi
}

# Rust
rust_setenv() {
  # ustc
  # export RUSTUP_DIST_SERVER=https://mirrors.ustc.edu.cn/rust-static
  # export RUSTUP_UPDATE_ROOT=https://mirrors.ustc.edu.cn/rust-static/rustup

  # tuna
  export RUSTUP_DIST_SERVER=https://mirrors.tuna.tsinghua.edu.cn/rustup
  export RUSTUP_UPDATE_ROOT=https://mirrors.tuna.tsinghua.edu.cn/rustup/rustup

  export RUSTUP_HOME=$HOME/.rustup
  export CARGO_HOME=$HOME/.cargo
  export RUST_BACKTRACE=full  # 0 1 full

  if [ -f $HOME/.cargo/env ]; then
    . $HOME/.cargo/env
  fi
  if [ -d $HOME/.cargo/bin/ ]; then
    export PATH="$HOME/.cargo/bin:$PATH"
    if [ "$OME_OS" = "$OS_CYGWIN" ] || [ "$OME_OS" = "$OS_MSYS2" ]; then
      export PATH="`cygpath -m $HOME/.cargo/bin`:$PATH"
    fi
    export RUST_SRC_PATH="$(rustc --print sysroot)/lib/rustlib/src/rust/src"
  fi
}
rust_setenv
