#!/usr/bin/env sh

sdl_install() {
get_os_type
case $OME_OS in
  # Linux
  # $OS_DEBIAN) ;;
  # $OS_UBUNTU) ;;
  $OS_DEBIAN|$OS_UBUNTU) ;;
  # $OS_REDHAT) ;;
  # $OS_FEDORA) ;;
  $OS_REDHAT|$OS_FEDORA) ;;
  $OS_ARCH) sudo pacman -S sdl2 sdl2_gfx sdl2_image sdl2_mixer sdl2_net sdl2_ttf;;
  $OS_GENTOO) ;;
  $OS_SUSE) ;;
  $OS_SLACKWARE) ;;
  $OS_NIXOS) ;;
  $OS_VOID) ;;
  $OS_ALPINE) ;;
  $OS_MAGEIA) ;;
  $OS_SLITAZ) ;;
  $OS_GUIXSD) ;;
  # Unix
  $OS_MACOS) ;;
  $OS_AIX) ;;
  $OS_SOLARIS) ;;
  $OS_FREEBSD) ;;
  $OS_OPENBSD) ;;
  $OS_NETBSD) ;;
  $OS_DFBSD) ;;
  # Windows
  $OS_CYGWIN) ;;
  $OS_MSYS2) ;;
  # Other
  $OS_UNKNOW) ;;
esac

}

sdl_uninstall() {
  echo_error "'sdl_uninstall' not implemented"
}

sdl_exist_p() {
  echo_error "'sdl_exist_p' not implemented"
}

sdl_info() {
  echo_error ""
}
