#!/usr/bin/env sh

toccata_install() {
    github_upgrade Toccata-Lang/toccata $OME_REPO/toccata
    cd $OME_REPO/toccata/
    
    # Compile core.c
    clang -O3 -g -fno-objc-arc -std=c99 -c core.c

    # Compile the Toccata compiler itself
    clang -O3 -g -fno-objc-arc -o toccata -std=c99 core.o toccata.c -lpthread
}

toccata_uninstall() {
    echo_error "'toccata_uninstall' not implemented"
}

toccata_exist_p() {
    echo_error "'toccata_exist_p' not implemented"
}

toccata_info() {
    echo_error ""
}

toccata_set_env() {
    # Set the TOCCATA_DIR environment variable to the directory that contains core.toc
    export TOCCATA_DIR=$OME_REPO/toccata

    # Add that same directory to the C_INCLUDE_PATH environment variable
    export C_INCLUDE_PATH=$C_INCLUDE_PATH:$TOCCATA_DIR

    # For convenience, make sure the toccata executable is on the $PATH.
    export PATH=$PATH:$TOCCATA_DIR
}
toccata_set_env
