#!/usr/bin/env sh

ttf_install() {
  get_os_type
  case $OME_OS in
    $OS_UNKNOW) ;;
    $OS_MACOS)
      brem install ttf-bitstream-vera
      ;;
    $OS_CYGWIN) ;;
    $OS_MSYS2) ;;
    $OS_ARCH)
      pacman -S ttf-bitstream-vera
      ;;
    $OS_DEBIAN|$OS_UBUNTU)
      sudo apt-get install -y ttf-mscorefonts_installer ttf-bitstream-vera
      ;;
    $OS_REDHAT|$OS_FEDORA) ;;
    $OS_FREEBSD) ;;
  esac
}

ttf_uninstall() {
  echo_error "'ttf_uninstall' not implemented"
}

ttf_exist_p() {
  echo_error "'ttf_exist_p' not implemented"
}

ttf_info() {
  echo_error ""
}
