#!/usr/bin/env sh

ue4_install() {
    github-ssh_upgrade EpicGames/UnrealEngine $DEV_ROOT/ue4/UnrealEngine 1 4.21
    cd $DEV_ROOT/ue4/UnrealEngine/
    ./Setup.sh
    ./GenerateProjectFiles.sh
}

ue4_uninstall() {
    echo_error "'ue4_uninstall' not implemented"
}

ue4_exist_p() {
    echo_error "'ue4_exist_p' not implemented"
}

ue4_info() {
    echo_error ""
}
