#!/usr/bin/env sh

verona_install() {
    github_upgrade microsoft/verona $OME_REPO/verona
    cd $OME_REPO/verona
    mkdir -p build_ninja
    cd build_ninja
    cmake .. -GNinja \
          -DCMAKE_INSTALL_PREFIX=$OME_PREFIX/bin \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_C_COMPILER=clang \
          -DCMAKE_CXX_COMPILER=clang++

    # cmake --build . --use-stderr --config Release --target install
    ninja install
}

verona_uninstall() {
    echo_error "'verona_uninstall' not implemented"
}

verona_exist_p() {
    echo_error "'verona_exist_p' not implemented"
}

verona_info() {
    echo_error ""
}
