#!/usr/bin/env sh

wps_install() {
  get_os_type
  case $OME_OS in
    # Linux
    # $OS_DEBIAN) ;;
    # $OS_UBUNTU) ;;
    $OS_DEBIAN|$OS_UBUNTU) ;;
    # $OS_REDHAT) ;;
    # $OS_FEDORA) ;;
    $OS_REDHAT|$OS_FEDORA) ;;
    $OS_ARCH) trizen -S wps-office ;;
    $OS_GENTOO) ;;
    $OS_SUSE)
      readp "Tumbleweed?"
      if [ $? -eq 1 ]; then
        sudo zypper addrepo https://download.opensuse.org/repositories/home:opensuse_zh/openSUSE_Tumbleweed/home:opensuse_zh.repo
      else
        sudo zypper addrepo https://download.opensuse.org/repositories/home:opensuse_zh/openSUSE_Leap_${releasever}/home:opensuse_zh.repo
      fi
      sudo zypper refresh
      sudo zypper install wps-office
      ;;
    $OS_SLACKWARE) ;;
    $OS_NIXOS) ;;
    $OS_VOID) ;;
    $OS_ALPINE) ;;
    $OS_MAGEIA) ;;
    $OS_SLITAZ) ;;
    $OS_GUIXSD) ;;
    # Unix
    $OS_MACOS) ;;
    $OS_AIX) ;;
    $OS_SOLARIS) ;;
    $OS_FREEBSD) ;;
    $OS_OPENBSD) ;;
    $OS_NETBSD) ;;
    $OS_DFBSD) ;;
    # Windows
    $OS_CYGWIN) ;;
    $OS_MSYS2) ;;
    # Other
    $OS_UNKNOW) ;;
  esac
}

wps_uninstall() {
  echo_error "'wps_uninstall' not implemented"
}

wps_exist_p() {
  echo_error "'wps_exist_p' not implemented"
}

wps_info() {
  echo_error ""
}
