#!/usr/bin/env sh
install_zig_language_server() {
  github_upgrade zigtools/zls $OME_REPO/zls
  cd $OME_REPO/zls
  zig build

  # To configure ZLS:
  zig build config
}

zig_install() {
  github_upgrade ziglang/zig $OME_REPO/zig
  cd $OME_REPO/zig
  mkdir -p build_ninja
  cd build_ninja
  cmake .. -GNinja \
        -DCMAKE_INSTALL_PREFIX=$OME_PREFIX \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_C_COMPILER=clang \
        -DCMAKE_CXX_COMPILER=clang++

  # cmake --build . --use-stderr --config Release --target install
  ninja install

  tip "install Zig language server"
  install_zig_language_server
}

zig_uninstall() {
  echo_error "'zig_uninstall' not implemented"
}

zig_exist_p() {
  echo_error "'zig_exist_p' not implemented"
}

zig_info() {
  echo_error ""
}
